
export const studyCountries = [
  { name: "United States", flag: "🇺🇸" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "France", flag: "🇫🇷" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "Netherlands", flag: "🇳🇱" },
  { name: "Switzerland", flag: "🇨🇭" },
  { name: "Singapore", flag: "🇸🇬" },
  { name: "Sweden", flag: "🇸🇪" },
  { name: "New Zealand", flag: "🇳🇿" },
  { name: "China", flag: "🇨🇳" },
  { name: "South Korea", flag: "🇰🇷" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Ireland", flag: "🇮🇪" },
  { name: "Finland", flag: "🇫🇮" },
  { name: "Denmark", flag: "🇩🇰" },
  { name: "Norway", flag: "🇳🇴" },
  { name: "Belgium", flag: "🇧🇪" },
  { name: "Austria", flag: "🇦🇹" },
  { name: "Hong Kong", flag: "🇭🇰" },
  { name: "Malaysia", flag: "🇲🇾" },
  { name: "United Arab Emirates", flag: "🇦🇪" }
];

export const studyLevels = [
  "Bachelor's Degree",
  "Master's Degree",
  "PhD",
  "MBA",
  "Professional Degree",
  "Diploma/Certificate",
  "Associate Degree",
];

export const studyFields = [
  "Computer Science and Engineering",
  "Business Administration",
  "Medicine and Health Sciences",
  "Law",
  "Economics",
  "Psychology",
  "Education",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Physics",
  "Mathematics",
  "Chemistry",
  "Biology",
  "Environmental Science",
  "Sociology",
  "Political Science",
  "International Relations",
  "Architecture",
  "Fine Arts",
  "Design",
  "Music",
  "Film and Media Studies",
  "Communications",
  "Journalism",
  "English Literature",
  "History",
  "Geography",
  "Philosophy",
  "Linguistics",
  "Anthropology",
  "Archaeology",
  "Agriculture",
  "Veterinary Science",
  "Nursing",
  "Pharmacy",
  "Dentistry",
  "Accounting and Finance",
  "Marketing",
  "Human Resources",
  "Information Systems",
  "Data Science and Analytics",
  "Artificial Intelligence",
  "Cybersecurity",
  "Biotechnology",
  "Public Health",
  "Social Work",
  "Hospitality and Tourism Management"
];
