// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujwedssjnxbffjncazou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqd2Vkc3NqbnhiZmZqbmNhem91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTEyNTksImV4cCI6MjA2MzYyNzI1OX0.aR-dXWI9VMUPryD_Zrw7NKDO47HBWSjhb_1mYwytRv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);